### ISSUE TITLE
sci-biology/fsl-6 topup errors

### ISSUE THREAD

**Issue by AbstractMethod** [gentoo/sci#991]
@TheChymera 

Ran into a problem running the `topup` command with fsl-6.0.2-r1 -- error follow below.

`topup` and `eddy` are critical to my data, so I rolled back to a (local) version of 5.0.11 (with my own modified cuda patch for eddy, similar to what I PR'ed as #973), which works fine.

I should also point out that my local version of 5.0.11 installs into the fsl default installation location of `/usr/local/fsl`, rather than the `/usr/share/fsl` location that 6.0.2-r1 uses.

```
$ topup -v --imain=b0 --datain=acqparams.txt --config=b02b0.cnf --out=topup_results --iout=hifi_b0
Segmentation violation, Address not mapped, Offending address = (nil)
topup  [0x558304c475d3]         
topup  [0x558304c476f2]         
topup  [0x558304bf935a]         
topup  [0x558304bb3d50]         
/lib64/libc.so.6 __libc_start_main [0x7f44b4dd3e5e]
topup  [0x558304bc63aa]
```

**Comment by AbstractMethod** [comment]
As I see it, there is 1 of 3 possible causes:

1. My installation is borked for some strange reason (although I did try re-emerging fsl -- same error as above) and this is not a problem

1. The changes made to the installation directory is making `topup` unhappy.

1. Upstream fsl-6-* is broken, while fsl-5-* is OK (highly unlikely).

**Comment by TheChymera** [comment]
@AbstractMethod Sadly I do not have a machine with FSL configured with CUDA support on which I can test this, perhaps @Jimmy2027 could help try and reproduce this? Or is `topup` CUDA independent? If so, if you share your data I can test this :)

> 1. My installation is borked for some strange reason (although I did try re-emerging fsl -- same error as above) and this is not a problem.

Possible. You could try to rebuild, `Segmentation violation` certainly doesn't sound like a library path issue.

> 2. The changes made to the installation directory is making topup unhappy.

Unlikely, given the error message.

> 3. Upstream fsl-6-* is broken, while fsl-5-* is OK (highly unlikely).

I wouldn't say *highly* unlikely :) Have you reported this to FSL upstream? I won't ping Paul this time, we're kind-of overdoing it :D

**Comment by AbstractMethod** [comment]
@TheChymera yeah, ```topup``` is CUDA independent (uses only a single-thread as far as I can tell).  It fails for me within 30 seconds or so of running on fsl-6.

Can provide data -- will need to transfer about 50 MB.  What's the best way to get it to you?

**Comment by TheChymera** [comment]
@AbstractMethod can you upload the archive somewhere, like, do you have some server space? If not I remember there's some free file sharing services around where you can just send me a link.

**Comment by AbstractMethod** [comment]
@TheChymera Uploading to my Google Drive -- you should receive an email invitation shortly.  Just download b0.nii.gz and the acqparams.txt files -- the parameters on the topup command are either configuration or for output files.

**Comment by TheChymera** [comment]
@AbstractMethod could you also send me `b02b0.cnf` then?

**Comment by AbstractMethod** [comment]
@TheChymera  You shouldn't need it?  It comes with fsl and is the default configuration file for ```topup```.  Should reside in ```${FSLDIR}/etc/flirtsch/```.  If you just reference it directly like I have on the command line above it should work.

**Comment by TheChymera** [comment]
@AbstractMethod could reproduce, so it's not your installation in particular which is wonky. Still, I highly doubt this has to do with the installation dir... Did it work before the latest changes from 21789df887204e7b98393fb115982ee36a71d8c1 — i.e. `=fsl-6.0.2`, which is still in the tree?


```
chymera@silenthost ~/test_topup $ topup -v --imain=b0 --datain=acqparams.txt --config=b02b0.cnf --out=topup_results --iout=hifi_b0
Segmentation violation, Address not mapped, Offending address = 0x8
topup  [0x558050975029]
topup  [0x558050975132]
topup  [0x55805090eaac]
topup  [0x5580508a8ac0]
/lib64/libc.so.6 __libc_start_main [0x7fbbc94cfe0a]
topup  [0x5580508d0cda]
```

**Comment by AbstractMethod** [comment]
@TheChymera OK, iinstalled fsl-6.0.2 and have the same error:

    topup -v --imain=../b0 --datain=../acqparams.txt --config=b02b0.cnf --out=topup_results --iout=hifi_b0
    Segmentation violation, Address not mapped, Offending address = (nil)
    topup  [0x555b61e405a3]
    topup  [0x555b61e406c2]
    topup  [0x555b61df234a]
    topup  [0x555b61dacd40]
    /lib64/libc.so.6 __libc_start_main [0x7fd8bc0cbe5e]
    topup  [0x555b61dbf39a]

Also confirmed on different ```b0``` dataset.

**Comment by AbstractMethod** [comment]
I saw similar errors with ```topup``` on the FSL list archive, so I posted as well.  Let's see if I can get verification upstream -- this may not be a problem with Gentoo at all.

**Comment by TheChymera** [comment]
@AbstractMethod I mean if we've exhausted all other options, I guess we could ask Paul for help again...

**Comment by AbstractMethod** [comment]
@TheChymera Heard back from upstream.  They've been unable to reproduce the problem with the same dataset, so it looks like it's on our end.

**Comment by TheChymera** [comment]
@AbstractMethod any leads on what might be wrong?

**Comment by AbstractMethod** [comment]
@TheChymera no sorry.  Was working on a abstract deadline this week.  Of the 3 possible sources I gave above seems like 2 have been exhausted.  Bu the installation directory seems highly unlikely to be the problem.  I guess we can try to loop Paul back in to help?

**Comment by TheChymera** [comment]
Hi @pauldmccarthy , we're having an issue with `topup` giving a segfault with a pretty standard minimal usage example:

```
wget https://chymera.eu/debug/FSL/test_topup.tar.xz
tar xvf test_topup.tar.xz
cd test_topup
topup -v --imain=b0 --datain=acqparams.txt --config=b02b0.cnf --out=topup_results --iout=hifi_b0
```

which seems specific to the results of our build instructions.
Could you help us out?
As always, many thanks :)

**Comment by pauldmccarthy** [comment]
I can't reproduce the error on my machine (Ubuntu 18.04, using an official FSL 6.0.4 installation)...

@AbstractMethod I'm just looking back through your mailing list post - you reproduced with 6.0.4 - I presume that you also compiled this from source? Was it vaniila, or did you apply any gentoo patches to it? Do you still have the `$FSLDIR/build.log` from that installation?

Some possible explanations that I can think of:

 - Much of the FSL code base is old, and is expected to be compiled against the `-ansi` (a.k.a `-std=c++98`) standard. If you are compiling against a newer standard, you may end up with behavioural differences at runtime. Just the other day I came across a bug which did not manifest itself when compiling with `-ansi`, but which did occur when compiling with any newer standard, whereby the expression `-varname` for an `unsigned int varname` would be coerced to a signed type in `-ansi`, but would wrap-around in `-std=c++11`.
 - There were substantial changes from FSL 5.0.11 to 6.0.2, namely a migration from the old [newmat](http://www.robertnz.net/nm10.htm#refer) linear algebra library to the more modern [armadillo](http://arma.sourceforge.net/), via a horrible translation layer called [armawrap](https://git.fmrib.ox.ac.uk/fsl/armawrap/). Armadillo is complicated in that it is a heavily templated header-only library, meaning that all data structures will be compiled separately into every executable and statically or dynamically linked library. If different binaries (libraries or executables) which use the same data structures are compiled in different ways, you can find yourself in a scenario where incompatible versions of the same data structure are baked into each binary (incompatible w.r.t. e.g. struct layout, padding, etc). This can lead to horrible issues at runtime.

We're in the process of setting up a standardised/automated build system (and moving to dynamic, rather than static linking) - this wil hopefully be in place in the next 6 months, and will hopefully make things easier for the long suffering FSL downstream folk.

**Comment by AbstractMethod** [comment]
@pauldmccarthy Yeah, I reproduced with 6.0.4, but this was with the Gentoo patches (i.e. I dropped in the 6.0.4 codebase into a local overlay), so it has all the Gentoo patches and installation directory, etc.  I don't have the $FSLDIR/build.log anymore, but I can rebuild and send that to you if you'd like.

**Comment by AbstractMethod** [comment]
OK, I've built fsl-6.0.4.ebuild.  My build log is attached:

[build.log.txt](https://github.com/gentoo/sci/files/5740566/build.log.txt)

**Comment by AbstractMethod** [comment]
@TheChymera OK, so I followed @pauldmccarthy suggestion, and modified the Makefile for ```topup``` by adding ```-std=c++98``` explicitly to the compile flags.  I was then able to run the example I provided above to completion.

Looking through the ```build.log``` I provided above, it seems the ```-std=``` option is being set differently depending on the module.  Sometimes it's ```gnu99```, sometimes ```c++11```, ```c99```, ```c++98```, etc.  Or as in the case of the original ```topup``` not set at all.

Should that not be standard across all the modules, and thus something like ```c++98``` set globally?

**Comment by AbstractMethod** [comment]
For completion, here is the patch I applied to topup to make it run correctly:

```
diff -Naur fsl.orig/src/topup/Makefile fsl/src/topup/Makefile
--- fsl.orig/src/topup/Makefile	2020-12-28 16:19:18.354205281 -0500
+++ fsl/src/topup/Makefile	2020-12-28 16:20:37.185203441 -0500
@@ -2,7 +2,7 @@
 
 PROJNAME=topup
 
-USRINCFLAGS=-I${INC_NEWMAT} -I${INC_BOOST} -I${INC_ZLIB} -I${INC_PROB}
+USRINCFLAGS=-std=c++98 -I${INC_NEWMAT} -I${INC_BOOST} -I${INC_ZLIB} -I${INC_PROB}
 USRLDFLAGS=-L${LIB_NEWMAT} -L${LIB_ZLIB} -L${LIB_PROB}
 
 OBJS=topup_matrices.o topup_file_io.o topup_costfunctions.o topupfns.o topup.o
```

I admit it's a bit ugly to add the flag to ```USRINCFLAGS``` but at least it works.

**Comment by TheChymera** [comment]
@AbstractMethod would it not be possible to export the variable in `src_compile()`? or would inidividual makefiles still overwrite this? If the latter — is there no pattern which could be `sed`-ed to make this homogeneous?

Bottom of the pile fix is to just submit a PR for a -r2 build with your patch for this specific file. But maybe there's other functions which fail similarly, and we'd be better served by a more general fix?

**Comment by kiwifb** [comment]
Ideally, you should use the flag-o-matic` eclass and append the flag but here changing
```
export USERCXXFLAGS="${CXXFLAGS}"
```
to 
```
export USERCXXFLAGS="${CXXFLAGS} -std=c++98"
```
in src_compile could be the way to go.

**Comment by pauldmccarthy** [comment]
Sorry for the silence, I got caught up with some DIY and other things over the holidays. I'll try again to reproduce on my development build and identify the underlying cause - . And yes - the `-std` used for different projects does differ, because there has been limited standardisation across development of different parts of FSL. So some projects will require e.g. `-std=c++11`. But the defaults for the official FSL release are `-std=c99` (C) and `-ansi` (C++).

In the new build system I've been working on, I'm intending to make `-std=c++11` the default, so hopefully our test suite will uncover any other issues which are similar to this.

**Comment by AbstractMethod** [comment]
Hmm... OK well based on @pauldmccarthy then we should not globally make it ```-std=c++98``` since we might break other projects which require a different standard.  And since he's intending to make ```-std=c+11``` the default eventually, then maybe we can make do for now with a quick fix for just ```topup``` and leave it there.

I agree this is the least esthetically pleasing option.

**Comment by pauldmccarthy** [comment]
Actually, you may wish to set `-std=c++98` as the global default, as your build system would then match the official one, and the `-std` should already be explicitly set in the `Makefile` for projects which require a different standard - `eddy` is the first one that comes to mind - I'm fairly sure that it already uses `-std=c++11` ..

**Comment by AbstractMethod** [comment]
OK cool -- thanks @pauldmccarthy.

So based on that information, and the fact that ```gcc``` will take the last argument of mutually exclusive options (https://stackoverflow.com/questions/40563269/passing-multiple-std-switches-to-g), what we should do in ```src_compile``` is actually:

```
export USERCXXFLAGS="-std=c++98 ${CXXFLAGS}"
```

This way, if ```-std``` is not specified by the Makefile, it gets set to ```-std=c++98```.  If it is explicitly set, then it should overwrite the global default.

I'll give that a shot in my local overlay and see how it goes.  If it fails we can try something more complicated.

**Comment by AbstractMethod** [comment]
Unfortunately, this didn't work:

```
Making project src/utils
 
Building dependency file depend.mk
/bin/rm -f /tmp/fslgrot *.o *.a *.exe core depend.mk
/bin/rm -f /tmp/fslgrot  
Building dependency file depend.mk
x86_64-pc-linux-gnu-g++ -c     -DBUILDSTRING="6.0.4:ddd0a010" -std=c++11    -I/var/tmp/portage/sci-biology/fsl-6.0.4/work/fsl/extras/include/armawrap/armawrap -DARMA_USE_LAPACK -DARMA_USE_BLAS -DARMA_64BIT_WORD -I. -I/var/tmp/portage/sci-biology/fsl-6.0.4/work/fsl/include -I/var/tmp/portage/sci-biology/fsl-6.0.4/work/fsl/include  -std=c++98 -march=native -O2 -pipe -fomit-frame-pointer FSLProfiler.cpp -o FSLProfiler.o
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/chrono:35,
                 from FSLProfiler.cpp:9:
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This su
```

From the relevant Makefile:

```USRCXXFLAGS = -DBUILDSTRING=${BUILDSTRING} -std=c++11 ```

which is being prepended to the `gcc` command line before ```USERCXXFLAGS``` unfortunately.

@kiwifb @TheChymera on how to fix easily?

**Comment by pauldmccarthy** [comment]
Yep, so the `utils` project requires C++11. In 6.0.4, the vanilla `utils/Makefile` has `USRCXXFLAGS=... -std=c++11`.

The vanilla 6.0.4 sources are already set up such that `-ansi` is the default (added to `ANSI_FLAGS` within `$FSLDIR/config/buildSettings.mk`, whcih is a big mess, but I've cleaned it up substantially in my dev version), but can be overridden in the `Makefile` for a given project via `USRCXXFLAGS`. This works, because the final `CXXFLAGS` are constructed (within `$FSLDIR/config/common/vars.mk`) such that `ANSI_FLAGS` comes first, and `USRCXXFLAGS` second so, as you described, the latter takes precedence.

**Comment by AbstractMethod** [comment]
OK, I think I got everything finally built.  I modified ```src_compile``` to include:

```
export ANSI_CFLAGS="-std=c99"
export ANSI_CXXFLAGS="-std=c++98"
```
I also had to patch the Makefiles for ```flameo``` and ```melodic``` by adding:

```USRCXXFLAGS = -std=c++11```

so that they compiled (```melodic``` requires the newer standard because of openmp I guess?)

@TheChymera : does this sound OK?  Should I submit a PR?  Note that I've only been working with the 6.0.4 sources as requested by the FSL listserv.  Or would you rather we just issue a PR for 6.0.2?

**Comment by TheChymera** [comment]
@AbstractMethod either is fine. Though if you version bump, it might be worth considering whether we can get it to work with `fslpy-3*` as seen in [the other issue](https://github.com/gentoo/sci/issues/1047). If that is the case, it would also make sense to mark `fsl-6.0.2` as depending on fslpy-2 and remove the hard mask.

**Comment by AbstractMethod** [comment]
@TheChymera Your version bump solution is a bit more complicated, but I like it better.

I'll set to work on it -- shouldn't be too bad.

**Comment by AbstractMethod** [comment]
@TheChymera: OK - submitted PR #1049 for this issue for version 6.0.4.

In addition to the fixes above for the --std stuff:

- removed the file collisions from fsl-6.0.4 for the new versions in fslpy-3.4.0
- removed the hardmask on fslpy-3.4.0
- added a block on fsl-6.0.4 for <fslpy-3
- added a block on fsl-6.0.2* for >=fslpy-3
